<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_F6BMAFNZEe6U0-1x786E9g" name="Diagrama del proceso de Validacion" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_F6BMAVNZEe6U0-1x786E9g" name="Proceso de Validacion">
      <elements xmi:type="process:Lane" xmi:id="_F6BMAlNZEe6U0-1x786E9g" name="Validador" actor="_F6BMG1NZEe6U0-1x786E9g">
        <elements xmi:type="process:StartEvent" xmi:id="_F6BMA1NZEe6U0-1x786E9g" name="Inicio1" outgoing="_F6BMGFNZEe6U0-1x786E9g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F6BMBFNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F6BMBVNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F6BMBlNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_F6BMB1NZEe6U0-1x786E9g" name="revisar solicitud" outgoing="_OYAE9FNZEe6U0-1x786E9g" incoming="_F6BMGFNZEe6U0-1x786E9g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F6BMCFNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F6BMCVNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F6BMClNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_F6BMC1NZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_F6BMDFNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_F6BMDVNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_F6BMDlNZEe6U0-1x786E9g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_F6BMD1NZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_F6BMEFNZEe6U0-1x786E9g">
            <targetForm xmi:type="expression:Expression" xmi:id="_2x2wUFgJEe6D6Ktgfk4Obg" name="ValidacionForm" content="6c88bbad-6a9f-4a21-a297-faed2bc3c84e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_F6BMElNZEe6U0-1x786E9g">
            <inputs xmi:type="process:ContractInput" xmi:id="_PgIzoFZ4Ee620djLttxCTQ" name="statusInput">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_PgIzoVZ4Ee620djLttxCTQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_F6BME1NZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_5qk-MFNZEe6U0-1x786E9g" name="fin validacion" incoming="_6wJfIFNZEe6U0-1x786E9g _7ER8EFNZEe6U0-1x786E9g _7ZVmEFNZEe6U0-1x786E9g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5qllQVNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5qllQFNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5qllQlNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_8YTckFZ2Ee620djLttxCTQ" name="correo aceptacion" outgoing="_7ZVmEFNZEe6U0-1x786E9g" incoming="_vz7CIVNZEe6U0-1x786E9g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vz6bElNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vz6bEVNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vz6bE1NZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_vz6bFFNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_vz6bFVNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_vz6bFlNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_vz6bGFNZEe6U0-1x786E9g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_vz6bF1NZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_8ucrsFZ2Ee620djLttxCTQ" name="correo rechazo" outgoing="_7ER8EFNZEe6U0-1x786E9g" incoming="_vQm5s1NZEe6U0-1x786E9g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vQmSolNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vQmSoVNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vQmSo1NZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_vQmSpFNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_vQmSpVNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_vQmSplNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_vQmSqFNZEe6U0-1x786E9g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_vQmSp1NZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_9JWfAFZ2Ee620djLttxCTQ" name="correo correción" outgoing="_6wJfIFNZEe6U0-1x786E9g" incoming="_usguK1NZEe6U0-1x786E9g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_usguIVNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_usguIFNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_usguIlNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_usguI1NZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_usguJFNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_usguJVNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_usguJ1NZEe6U0-1x786E9g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_usguJlNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_7gxiMFZ3Ee620djLttxCTQ" name="es aprobado?" outgoing="_usguK1NZEe6U0-1x786E9g _vQm5s1NZEe6U0-1x786E9g _vz7CIVNZEe6U0-1x786E9g" incoming="_OYAE9FNZEe6U0-1x786E9g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OX_d4lNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OX_d4VNZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OX_d41NZEe6U0-1x786E9g" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_UVbssFNZEe6U0-1x786E9g" name="solicitud" dataType="_F6BMNFNZEe6U0-1x786E9g" className="com.company.model.Solicitud">
        <defaultValue xmi:type="expression:Expression" xmi:id="_UVbssVNZEe6U0-1x786E9g" name="solicitudPersistenceId" content="solicitudDAO.findByPersistenceId(solicitudId)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Solicitud">
          <referencedElements xmi:type="expression:Expression" xmi:id="_n1hT4FgJEe6D6Ktgfk4Obg" name="solicitudDAO" content="solicitudDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.SolicitudDAO" returnTypeFixed="true"/>
          <referencedElements xmi:type="process:ContractInput" xmi:id="_n1hT4VgJEe6D6Ktgfk4Obg" name="solicitudId" type="LONG">
            <mapping xmi:type="process:ContractInputMapping" xmi:id="_n1hT4lgJEe6D6Ktgfk4Obg"/>
          </referencedElements>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_F6BMFFNZEe6U0-1x786E9g">
        <targetForm xmi:type="expression:Expression" xmi:id="_9epx4FZ8Ee620djLttxCTQ" name="ValidacionForm" content="6c88bbad-6a9f-4a21-a297-faed2bc3c84e" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_F6BMFlNZEe6U0-1x786E9g">
        <targetForm xmi:type="expression:Expression" xmi:id="_F6BMF1NZEe6U0-1x786E9g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_F6BMGFNZEe6U0-1x786E9g" target="_F6BMB1NZEe6U0-1x786E9g" source="_F6BMA1NZEe6U0-1x786E9g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_F6BMGVNZEe6U0-1x786E9g"/>
        <condition xmi:type="expression:Expression" xmi:id="_F6BMGlNZEe6U0-1x786E9g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OYAE9FNZEe6U0-1x786E9g" target="_7gxiMFZ3Ee620djLttxCTQ" source="_F6BMB1NZEe6U0-1x786E9g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OYAE9VNZEe6U0-1x786E9g"/>
        <condition xmi:type="expression:Expression" xmi:id="_OYAE9lNZEe6U0-1x786E9g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_usguK1NZEe6U0-1x786E9g" name="corregir" target="_9JWfAFZ2Ee620djLttxCTQ" source="_7gxiMFZ3Ee620djLttxCTQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_usguLFNZEe6U0-1x786E9g"/>
        <condition xmi:type="expression:Expression" xmi:id="_usguLVNZEe6U0-1x786E9g" name="estatusCorregir" content="solicitud.status == &quot;modificación&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_tiTQgFgJEe6D6Ktgfk4Obg" name="solicitud" dataType="_F6BMNFNZEe6U0-1x786E9g" className="com.company.model.Solicitud"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vQm5s1NZEe6U0-1x786E9g" name="no" target="_8ucrsFZ2Ee620djLttxCTQ" source="_7gxiMFZ3Ee620djLttxCTQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vQm5tFNZEe6U0-1x786E9g"/>
        <condition xmi:type="expression:Expression" xmi:id="_vQm5tVNZEe6U0-1x786E9g" name="estatusRechazado" content="solicitud.status == &quot;rechazada&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_u2Ho0FgJEe6D6Ktgfk4Obg" name="solicitud" dataType="_F6BMNFNZEe6U0-1x786E9g" className="com.company.model.Solicitud"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vz7CIVNZEe6U0-1x786E9g" name="si" target="_8YTckFZ2Ee620djLttxCTQ" source="_7gxiMFZ3Ee620djLttxCTQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vz7CIlNZEe6U0-1x786E9g"/>
        <condition xmi:type="expression:Expression" xmi:id="_vz7CI1NZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6wJfIFNZEe6U0-1x786E9g" target="_5qk-MFNZEe6U0-1x786E9g" source="_9JWfAFZ2Ee620djLttxCTQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6wJfIVNZEe6U0-1x786E9g"/>
        <condition xmi:type="expression:Expression" xmi:id="_6wJfIlNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7ER8EFNZEe6U0-1x786E9g" target="_5qk-MFNZEe6U0-1x786E9g" source="_8ucrsFZ2Ee620djLttxCTQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7ER8EVNZEe6U0-1x786E9g"/>
        <condition xmi:type="expression:Expression" xmi:id="_7ER8ElNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7ZVmEFNZEe6U0-1x786E9g" target="_5qk-MFNZEe6U0-1x786E9g" source="_8YTckFZ2Ee620djLttxCTQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7ZVmEVNZEe6U0-1x786E9g"/>
        <condition xmi:type="expression:Expression" xmi:id="_7ZVmElNZEe6U0-1x786E9g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_F6BMG1NZEe6U0-1x786E9g" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_F6BMHFNZEe6U0-1x786E9g">
        <inputs xmi:type="process:ContractInput" xmi:id="_fA-VEFgJEe6D6Ktgfk4Obg" name="solicitudId" type="LONG">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_fA-VEVgJEe6D6Ktgfk4Obg"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_F6BMHVNZEe6U0-1x786E9g">
        <name xmi:type="expression:Expression" xmi:id="_F6BMHlNZEe6U0-1x786E9g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_F6BMH1NZEe6U0-1x786E9g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_F6BMIFNZEe6U0-1x786E9g">
        <name xmi:type="expression:Expression" xmi:id="_F6BMIVNZEe6U0-1x786E9g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_F6BMIlNZEe6U0-1x786E9g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_F6BMI1NZEe6U0-1x786E9g">
        <name xmi:type="expression:Expression" xmi:id="_F6BMJFNZEe6U0-1x786E9g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_F6BMJVNZEe6U0-1x786E9g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_F6BMJlNZEe6U0-1x786E9g">
        <name xmi:type="expression:Expression" xmi:id="_F6BMJ1NZEe6U0-1x786E9g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_F6BMKFNZEe6U0-1x786E9g" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_F6BMKVNZEe6U0-1x786E9g">
        <name xmi:type="expression:Expression" xmi:id="_F6BMKlNZEe6U0-1x786E9g" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_F6BMK1NZEe6U0-1x786E9g" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_F6BMLFNZEe6U0-1x786E9g" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_F6BMLVNZEe6U0-1x786E9g" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_F6BMLlNZEe6U0-1x786E9g" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_F6BML1NZEe6U0-1x786E9g" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_F6BMMFNZEe6U0-1x786E9g" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_F6BMMVNZEe6U0-1x786E9g" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_F6BMMlNZEe6U0-1x786E9g" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_F6BMM1NZEe6U0-1x786E9g" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_F6BMNFNZEe6U0-1x786E9g" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_F6BMNVNZEe6U0-1x786E9g" type="Process" element="_F6BMAFNZEe6U0-1x786E9g" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_F6BMNlNZEe6U0-1x786E9g" type="2007" element="_F6BMAVNZEe6U0-1x786E9g">
      <children xmi:type="notation:DecorationNode" xmi:id="_F6BMN1NZEe6U0-1x786E9g" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_F6BMOFNZEe6U0-1x786E9g" type="7001">
        <children xmi:type="notation:Node" xmi:id="_F6BMOVNZEe6U0-1x786E9g" type="3007" element="_F6BMAlNZEe6U0-1x786E9g">
          <children xmi:type="notation:DecorationNode" xmi:id="_F6BMOlNZEe6U0-1x786E9g" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_F6BMO1NZEe6U0-1x786E9g" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_F6BMPFNZEe6U0-1x786E9g" type="3005" element="_F6BMB1NZEe6U0-1x786E9g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_F6BMPVNZEe6U0-1x786E9g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F6BMPlNZEe6U0-1x786E9g" x="158" y="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_F6BMP1NZEe6U0-1x786E9g" type="3002" element="_F6BMA1NZEe6U0-1x786E9g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_F6BMQFNZEe6U0-1x786E9g" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_F6BMQVNZEe6U0-1x786E9g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F6BMQlNZEe6U0-1x786E9g" x="60" y="114"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5qmMUFNZEe6U0-1x786E9g" type="3003" element="_5qk-MFNZEe6U0-1x786E9g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_5qmMUlNZEe6U0-1x786E9g" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_5qmMU1NZEe6U0-1x786E9g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5qmMUVNZEe6U0-1x786E9g" x="902" y="111"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8YhfAFZ2Ee620djLttxCTQ" type="3006" element="_8YTckFZ2Ee620djLttxCTQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8YiGEFZ2Ee620djLttxCTQ" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8YhfAVZ2Ee620djLttxCTQ" x="618" y="182" width="123" height="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8ucruVZ2Ee620djLttxCTQ" type="3006" element="_8ucrsFZ2Ee620djLttxCTQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8udSwFZ2Ee620djLttxCTQ" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8ucrulZ2Ee620djLttxCTQ" x="618" y="99" width="124" height="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9JWfCVZ2Ee620djLttxCTQ" type="3006" element="_9JWfAFZ2Ee620djLttxCTQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9JXGEFZ2Ee620djLttxCTQ" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9JWfClZ2Ee620djLttxCTQ" x="618" y="20" width="124" height="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7gyJQFZ3Ee620djLttxCTQ" type="3008" element="_7gxiMFZ3Ee620djLttxCTQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_7gyJQlZ3Ee620djLttxCTQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_7gyJQ1Z3Ee620djLttxCTQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7gyJQVZ3Ee620djLttxCTQ" x="396" y="94" width="42" height="42"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_F6BMQ1NZEe6U0-1x786E9g"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_F6BMRFNZEe6U0-1x786E9g" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_F6BMRVNZEe6U0-1x786E9g"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_F6BMRlNZEe6U0-1x786E9g"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F6BMR1NZEe6U0-1x786E9g" x="53" y="10" width="1032" height="283"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_F6BMSFNZEe6U0-1x786E9g"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_F6BMSVNZEe6U0-1x786E9g" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_F6BMSlNZEe6U0-1x786E9g"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_F6BMS1NZEe6U0-1x786E9g"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F6BMTFNZEe6U0-1x786E9g" width="1060" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_F6BMTVNZEe6U0-1x786E9g"/>
    <edges xmi:type="notation:Connector" xmi:id="_F6BMTlNZEe6U0-1x786E9g" type="4001" element="_F6BMGFNZEe6U0-1x786E9g" source="_F6BMP1NZEe6U0-1x786E9g" target="_F6BMPFNZEe6U0-1x786E9g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_F6BMT1NZEe6U0-1x786E9g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_F6BMUFNZEe6U0-1x786E9g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_F6BMUVNZEe6U0-1x786E9g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_F6BMUlNZEe6U0-1x786E9g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OYAE91NZEe6U0-1x786E9g" type="4001" element="_OYAE9FNZEe6U0-1x786E9g" source="_F6BMPFNZEe6U0-1x786E9g" target="_7gyJQFZ3Ee620djLttxCTQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OYAsAFNZEe6U0-1x786E9g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OYAsAVNZEe6U0-1x786E9g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OYAE-FNZEe6U0-1x786E9g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OYAE-VNZEe6U0-1x786E9g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ushVMFNZEe6U0-1x786E9g" type="4001" element="_usguK1NZEe6U0-1x786E9g" source="_7gyJQFZ3Ee620djLttxCTQ" target="_9JWfCVZ2Ee620djLttxCTQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ushVM1NZEe6U0-1x786E9g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ushVNFNZEe6U0-1x786E9g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ushVMVNZEe6U0-1x786E9g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ushVMlNZEe6U0-1x786E9g" points="[0, -21, -251, 49]$[0, -57, -251, 13]$[201, -57, -50, 13]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vQm5tlNZEe6U0-1x786E9g" type="4001" element="_vQm5s1NZEe6U0-1x786E9g" source="_7gyJQFZ3Ee620djLttxCTQ" target="_8ucruVZ2Ee620djLttxCTQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vQm5uVNZEe6U0-1x786E9g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vQm5ulNZEe6U0-1x786E9g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vQm5t1NZEe6U0-1x786E9g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vQm5uFNZEe6U0-1x786E9g" points="[10, 12, -253, -2]$[201, 12, -62, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vz7CJFNZEe6U0-1x786E9g" type="4001" element="_vz7CIVNZEe6U0-1x786E9g" source="_7gyJQFZ3Ee620djLttxCTQ" target="_8YhfAFZ2Ee620djLttxCTQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vz7CJ1NZEe6U0-1x786E9g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vz7CKFNZEe6U0-1x786E9g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vz7CJVNZEe6U0-1x786E9g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vz7CJlNZEe6U0-1x786E9g" points="[6, 16, -256, -81]$[6, 96, -256, -1]$[201, 96, -61, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6wJfI1NZEe6U0-1x786E9g" type="4001" element="_6wJfIFNZEe6U0-1x786E9g" source="_9JWfCVZ2Ee620djLttxCTQ" target="_5qmMUFNZEe6U0-1x786E9g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6wKGMFNZEe6U0-1x786E9g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6wKGMVNZEe6U0-1x786E9g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6wJfJFNZEe6U0-1x786E9g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6wJfJVNZEe6U0-1x786E9g" points="[0, 0, -188, -68]$[185, 66, -3, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6wKtQFNZEe6U0-1x786E9g" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6wKtQVNZEe6U0-1x786E9g" id="(0.16666666666666666,0.23333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7ER8E1NZEe6U0-1x786E9g" type="4001" element="_7ER8EFNZEe6U0-1x786E9g" source="_8ucruVZ2Ee620djLttxCTQ" target="_5qmMUFNZEe6U0-1x786E9g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7ESjIFNZEe6U0-1x786E9g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7ESjIVNZEe6U0-1x786E9g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7ER8FFNZEe6U0-1x786E9g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7ER8FVNZEe6U0-1x786E9g" points="[0, -6, -189, 0]$[188, -7, -1, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7ETKMFNZEe6U0-1x786E9g" id="(1.0,0.6)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7ETKMVNZEe6U0-1x786E9g" id="(0.03333333333333333,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7ZWNIFNZEe6U0-1x786E9g" type="4001" element="_7ZVmEFNZEe6U0-1x786E9g" source="_8YhfAFZ2Ee620djLttxCTQ" target="_5qmMUFNZEe6U0-1x786E9g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7ZWNI1NZEe6U0-1x786E9g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7ZWNJFNZEe6U0-1x786E9g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7ZWNIVNZEe6U0-1x786E9g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7ZWNIlNZEe6U0-1x786E9g" points="[0, 0, -204, 84]$[199, -70, -5, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7ZW0MFNZEe6U0-1x786E9g" id="(1.0,0.54)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
